-d C:\Users\kinchitc\Desktop\vga_controller_with_DACs_0414\impl\gwsynthesis\vga_controller.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\kinchitc\Desktop\vga_controller_with_DACs_0414\src\vga.cst
-cfg C:\Users\kinchitc\Desktop\vga_controller_with_DACs_0414\impl\pnr\device.cfg
-sdc C:\Users\kinchitc\Desktop\vga_controller_with_DACs_0414\src\clock.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 10
-global_freq 50.000
